language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

install: echo "skip 'gradle assemble' step"
script:
   - ./gradlew build

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  on:
    branch: master
    tags: true
    # deploy only with oraclejdk7
    condition: $JAVA_HOME = /usr/lib/jvm/java-7-oracle


